2017-11-03T13:54:39.0799679+05:00 0HL92J21CKASA:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:1796/api/values   (ca22a1cb)
2017-11-03T13:54:40.0416103+05:00 0HL92J21CKASA:00000001 [INF] Executing action method "Service.Controllers.ValuesController.Get (Service)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-11-03T13:54:49.8441550+05:00 0HL92J21CKASA:00000001 [INF] Executed action "Service.Controllers.ValuesController.Get (Service)" in 9893.4587ms (afa2e885)
2017-11-03T13:54:49.8861834+05:00 0HL92J21CKASA:00000001 [ERR] An unhandled exception has occurred while executing the request (cf926119)
Service.Core.AscConnectionException: Не удалось установить соединение с сервером
   at Service.Core.AscClient.StartClient()
   at Service.Core.AscClient.Reqvest[T](Message message)
   at Service.Controllers.ValuesController.Get()
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2017-11-03T13:54:50.2804463+05:00 0HL92J21CKASA:00000001 [INF] Request finished in 11218.9153ms 500 text/html; charset=utf-8 (791a596a)
2017-11-03T13:54:50.3945225+05:00 0HL92J21CKASA:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:1796/favicon.ico   (ca22a1cb)
2017-11-03T13:54:50.4005268+05:00 0HL92J21CKASA:00000002 [INF] Request finished in 5.5069ms 404  (791a596a)
2017-11-03T14:09:47.3354030+05:00 0HL92JAG8LTK2:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:1796/api/values   (ca22a1cb)
2017-11-03T14:09:47.9318019+05:00 0HL92JAG8LTK2:00000001 [INF] Executing action method "Service.Controllers.ValuesController.Get (Service)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-11-03T14:09:56.4334781+05:00 0HL92JAG8LTK2:00000001 [INF] Executed action "Service.Controllers.ValuesController.Get (Service)" in 8608.9597ms (afa2e885)
2017-11-03T14:09:56.4464864+05:00 0HL92JAG8LTK2:00000001 [ERR] An unhandled exception has occurred while executing the request (cf926119)
Service.Core.AscConnectionException: Не удалось установить соединение с сервером таймаут превышен
   at Service.Core.AscClient.StartClient()
   at Service.Core.AscClient.Reqvest[T](Message message)
   at Service.Controllers.ValuesController.Get()
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2017-11-03T14:09:56.6436180+05:00 0HL92JAG8LTK2:00000001 [INF] Request finished in 9325.7549ms 500 text/html; charset=utf-8 (791a596a)
2017-11-03T14:09:56.7536915+05:00 0HL92JAG8LTK2:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:1796/favicon.ico   (ca22a1cb)
2017-11-03T14:09:56.7596955+05:00 0HL92JAG8LTK2:00000002 [INF] Request finished in 5.6122ms 404  (791a596a)
2017-11-03T14:10:51.1620199+05:00 0HL92JB3F0NP9:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:1796/api/values   (ca22a1cb)
2017-11-03T14:10:51.4792317+05:00 0HL92JB3F0NP9:00000001 [INF] Executing action method "Service.Controllers.ValuesController.Get (Service)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-11-03T14:11:46.9342586+05:00 0HL92JBK5DMCF:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:1796/api/values   (ca22a1cb)
2017-11-03T14:11:47.2714841+05:00 0HL92JBK5DMCF:00000001 [INF] Executing action method "Service.Controllers.ValuesController.Get (Service)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-11-03T14:11:47.3025045+05:00 0HL92JBK5DMCF:00000001 [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2017-11-03T14:11:47.3565402+05:00 0HL92JBK5DMCF:00000001 [INF] Executed action "Service.Controllers.ValuesController.Get (Service)" in 136.4343ms (afa2e885)
2017-11-03T14:11:47.3675475+05:00 0HL92JBK5DMCF:00000001 [INF] Request finished in 444.1173ms 200 text/plain; charset=utf-8 (791a596a)
2017-11-03T14:11:47.3795559+05:00 0HL92JBK5DMCF:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:1796/favicon.ico   (ca22a1cb)
2017-11-03T14:11:47.3875613+05:00 0HL92JBK5DMCF:00000002 [INF] Request finished in 8.5284ms 404  (791a596a)
2017-11-03T14:12:16.8192125+05:00 0HL92JBT22RR1:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:1796/api/values   (ca22a1cb)
2017-11-03T14:12:17.0543692+05:00 0HL92JBT22RR1:00000001 [INF] Request finished in 250.2176ms 404  (791a596a)
2017-11-03T14:12:17.0623746+05:00 0HL92JBT22RR1:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:1796/favicon.ico   (ca22a1cb)
2017-11-03T14:12:17.0623746+05:00 0HL92JBT22RR1:00000002 [INF] Request finished in 0.6742ms 404  (791a596a)
2017-11-03T14:12:29.1734610+05:00 0HL92JBT22RR1:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:1796/values/Brigades   (ca22a1cb)
2017-11-03T14:12:29.2785308+05:00 0HL92JBT22RR1:00000003 [INF] Executing action method "Service.Controllers.ValuesController.Get (Service)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-11-03T14:12:29.3055492+05:00 0HL92JBT22RR1:00000003 [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2017-11-03T14:12:29.3355700+05:00 0HL92JBT22RR1:00000003 [INF] Executed action "Service.Controllers.ValuesController.Get (Service)" in 103.0274ms (afa2e885)
2017-11-03T14:12:29.3375709+05:00 0HL92JBT22RR1:00000003 [INF] Request finished in 163.922ms 200 text/plain; charset=utf-8 (791a596a)
